=== MLMatheus/schema-generator/schema_result.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "nome": {
            "type": "string"
        },
        "sobrenome": {
            "type": "string"
        },
        "sexo": {
            "type": "string"
        },
        "idade": {
            "type": "integer"
        },
        "altura": {
            "type": "number"
        },
        "robes": {
            "type": "array",
            "itens": {
                "type": "object"
            }
        },
        "gosta_de": {
            "type": "string"
        },
        "familiares": {
            "type": "array",
            "itens": {
                "type": "object",
                "properties": {
                    "nome": {
                        "type": "string"
                    },
                    "relacao": {
                        "type": "string"
                    }
                },
                "required": [
                    "nome",
                    "relacao"
                ]
            }
        },
        "nacionalidade": {
            "type": "string"
        }
    },
    "required": [
        "nome",
        "sobrenome",
        "sexo",
        "idade",
        "altura",
        "robes",
        "gosta_de",
        "familiares",
        "nacionalidade"
    ]
}

=== MLMatheus/schema-generator/schema.json
{
    "nome": "Matheus",
    "sobrenome": "Lima",
    "sexo": "m",
    "idade": 24,
    "altura": 1.70,
    "robes": [
        "cantar",
        "tocar",
        "Andar de bicicleta"
    ],
    "gosta_de": "musica boa",
    "familiares": [
        {
            "nome": "Maria Cineide",
            "relacao": "mae"
        },
        {
            "nome": "Romildo Izidio de Lima",
            "relacao": "pai"
        }
    ],
    "nacionalidade": "Brasil"
}
